apiVersion: v1
kind: Service
metadata:
  name: mubashersa-task-service
spec:
  type: NodePort
  selector:
    app: mubashersa-task-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080